name: backend-cd
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - starter/backend/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v3
    # Build
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: lint
      run: |
        pip install pipenv
        cd starter/backend
        pipenv install
        pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v3
    # Build
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install pipenv
      run: pip install pipenv
    - run: |
        cd starter/backend
        pipenv install
        pipenv run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Check Docker Version
        run: docker --version
      - name: Check AWS CLI Version
        run: aws --version
      - name: Install Kustomize
        run: |
          curl -s "https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest" | \
          grep "browser_download_url.*linux_amd64" | \
          cut -d : -f 2,3 | \
          tr -d \" | \
          xargs curl -LO
          # Assuming the downloaded file is in tar.gz format
          tar -zxvf kustomize_*.tar.gz
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.ECR_URL }}
      - name: Push docker image
        run: |
          cd starter/backend
          docker build --tag=$GITHUB_SHA .
          docker tag $GITHUB_SHA ${{vars.ECR_URL}}/backend:$GITHUB_SHA
          docker push ${{vars.ECR_URL}}/backend:$GITHUB_SHA
      - name: Deploy to kubenetes cluster
        run: |
          cd starter/backend/k8s
          aws eks update-kubeconfig --name cluster
          kustomize edit set image backend=${{vars.ECR_URL}}/backend:$GITHUB_SHA
          kustomize build | kubectl apply -k .  --validate=false