name: frontend-cd
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - starter/frontend/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: cd starter/frontend && npm ci
      - name: Run the linter
        run: cd starter/frontend && npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: cd starter/frontend && npm ci
      - name: Run tests
        run: cd starter/frontend && npm test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: deploy
        run: |
          cd starter/frontend
          docker build --build-arg=${{env.REACT_APP_MOVIE_API_URL}} --tag=$GITHUB_SHA .\
          docker tag $GITHUB_SHA ${{vars.ECR_URL}}/frontend:$GITHUB_SHA
          docker push ${{vars.ECR_URL}}/frontend:$GITHUB_SHA
          cd starter/frontend/k8s
          aws eks update-kubeconfig
          kustomize edit set image frontend=${{vars.ECR_URL}}/frontend:$GITHUB_SHA
          kustomize build | kubectl apply -f .
