name: Frontend Continuous Deployment
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - starter/frontend/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: cd starter/frontend && npm ci
      - name: Run the linter
        run: cd starter/frontend && npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: cd starter/frontend && npm ci
      - name: Run tests
        run: cd starter/frontend && npm test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    env:
      REACT_APP_MOVIE_API_URL: ${{vars.REACT_APP_MOVIE_API_URL}}
      # REACT_APP_MOVIE_API_URL: a6c2c3a8f787b442a89e6b4ca533d1d9-1542989495.us-east-1.elb.amazonaws.com  # Set your environment variable here
      ECR_URL: ${{ vars.ECR_URL }}  # Ensure this is set in your GitHub secrets
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Check Docker Version
        run: docker --version
      - name: Check AWS CLI Version
        run: aws --version
      - name: Install Kustomize
        run: |
          curl -s "https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest" | \
          grep "browser_download_url.*linux_amd64" | \
          cut -d : -f 2,3 | \
          tr -d \" | \
          xargs curl -LO
          # Assuming the downloaded file is in tar.gz format
          tar -zxvf kustomize_*.tar.gz
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.ECR_URL }}
      - name: Push docker image
        run: |
          cd starter/frontend
          docker build --build-arg REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }} --tag=$GITHUB_SHA .
          docker tag $GITHUB_SHA ${{ vars.ECR_URL }}/frontend:$GITHUB_SHA
          docker push ${{ vars.ECR_URL }}/frontend:$GITHUB_SHA
      - name: Deploy to kubernetes cluster
        run: |
          cd starter/frontend/k8s
          aws eks update-kubeconfig --name cluster
          kustomize edit set image frontend=${{ vars.ECR_URL }}/frontend:$GITHUB_SHA
          kustomize build | kubectl apply -k .
