name: frontend-ci

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - starter/frontend/**
env:
  REACT_APP_MOVIE_API_URL: http://localhost:5000

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: cd starter/frontend && npm ci
      - name: Run the linter
        run: cd starter/frontend && npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: cd starter/frontend && npm ci
      - name: Run tests
        run: cd starter/frontend && npm test

  build:
    needs: [lint, test]
      runs-on: ubuntu-latest
      steps:
        - name: docker build
          run: |
            cd starter/frontend
            docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
            docker run --name mp-frontend -p 3000:3000 -d mp-frontend
